name: education
description: An app build with the stacked framework

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  step_progress_indicator: ^1.0.2
  flutter_switch: ^0.3.2
  flutter_snake_navigationbar: ^0.6.1
  table_calendar: ^3.0.8
  comment_box: ^0.0.18
  syncfusion_flutter_sliders: ^26.1.38
  chips_choice: ^3.0.0
  flutter_feather_icons: ^2.0.0+1
  calender_picker: ^2.0.2
  flutter_credit_card: ^4.0.1
  pin_code_fields: ^8.0.1
  numeric_keyboard: ^1.1.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.4
  syncfusion_flutter_charts: ^26.1.38
  readmore: ^3.0.0
  video_player: ^2.6.0
  flutter_rating_bar: ^4.0.1
  local_auth: ^2.1.6
  carousel_slider: ^4.2.1
  pinput: ^5.0.0
  flip: ^2.0.0
  flip_card: ^0.7.0
  calendar_date_picker2: ^1.1.4
  fl_chart: ^0.68.0
  
  stacked: ^3.2.7
  stacked_services: ^1.0.0
  email_auth: ^2.0.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  image_picker: ^1.1.2
  firebase_storage: ^12.0.1
  email_otp: ^2.0.1
  shared_preferences:
  loading_animation_widget: ^1.2.0+4
  timeago: ^3.3.0
  cached_network_image: ^3.0.0
  syncfusion_flutter_pdfviewer: ^26.1.38
  file_picker: ^8.0.5
  pdf_viewer_plugin: ^2.0.1
  firebase_crashlytics: ^4.0.1
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^15.0.1
  get_it: ^7.6.4
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.2.0

  stacked_generator: ^1.0.0
  mockito: ^5.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


